import { ArrowRight, ArrowUpRight, Blocks, BookOpen, LayoutDashboard, Check, Terminal } from "lucide-react";
import * as UI from "@cortex/ui";

export function Home() {
  return <div className="home-page">
    <section className="landing-hero">
      <div className="landing-copy"><p className="eyebrow"><span className="status-dot" /> A REACT COMPONENT LIBRARY</p><h1>Build interfaces<br />with a clear<br /><span>point of view.</span></h1><p>66 components for dashboards, tools, and conversations. Explore the details, learn the patterns, and see how they work in a complete product.</p><div className="landing-actions"><UI.Button size="lg" asChild><a href="#/components">Browse components <ArrowRight /></a></UI.Button><UI.Button size="lg" variant="outline" asChild><a href="#/examples">Explore examples <ArrowUpRight /></a></UI.Button></div><div className="tech-line">REACT <span>/</span> TYPESCRIPT <span>/</span> TAILWIND CSS</div></div>
      <div className="product-preview" aria-label="Preview of a project dashboard"><div className="preview-top"><span><span className="status-dot" /> ORBIT / WORKSPACE</span><UI.Badge variant="outline">Preview</UI.Badge></div><div className="preview-body"><div className="demo-row justify-between"><div><p className="muted">Monday, October 5</p><h2>A little more progress.</h2></div><UI.Avatar><UI.AvatarFallback>AL</UI.AvatarFallback></UI.Avatar></div><div className="preview-metrics"><div><span className="muted">Tasks completed</span><strong>24<span className="muted"> / 32</span></strong><UI.Progress value={75} /></div><div><span className="muted">This week's focus</span><strong>18.5<span className="muted"> hrs</span></strong><div className="spark-bars" aria-hidden="true">{[30, 48, 42, 68, 58, 85, 74, 100, 88, 115, 98, 130].map((h, i) => <i key={i} style={{ height: h / 3 }} />)}</div></div></div><div className="preview-task"><span className="preview-check"><Check size={13} /></span><span>Design the account settings</span><UI.Badge variant="secondary">Done</UI.Badge></div><div className="preview-task"><span className="preview-check"><Check size={13} /></span><span>Review the component library</span><UI.Badge variant="secondary">Done</UI.Badge></div><div className="preview-task"><span className="preview-unchecked" /><span>Ship something useful</span><UI.Badge variant="outline">In progress</UI.Badge></div><a href="#/examples/projects" className="preview-link">Open the project example <ArrowUpRight size={15} /></a></div><div className="preview-bottom"><span className="signal-bars" /><span>BUILT WITH CORTEX UI</span></div></div>
    </section>
    <div className="library-strip"><span><strong>66</strong> components</span><span><strong>26</strong> interactive demos</span><span><strong>5</strong> product examples</span><span>One shared theme</span></div>
    <section className="home-section"><div className="section-heading"><div><p className="eyebrow">START EXPLORING</p><h2>A few ways in.</h2></div><p>Go from an individual control to a complete page.</p></div><div className="entry-grid">{[{icon: BookOpen, title: "Know your components", description: "Find the right control with usage notes, code samples, and variations for every component.", href: "/components", label: "Read the guide"}, {icon: Blocks, title: "Try every interaction", description: "The full component wall. Open a dialog, sort a table, or experiment with a conversation.", href: "/showcase", label: "Open the showcase"}, {icon: LayoutDashboard, title: "See the bigger picture", description: "Five realistic product pages, built from the same components. Explore working mock interactions.", href: "/examples", label: "Explore examples"}].map(({icon: Icon, ...item}) => <a className="entry-card" key={item.href} href={`#${item.href}`}><Icon size={23} /><h3>{item.title}</h3><p>{item.description}</p><span>{item.label}<ArrowUpRight size={16} /></span></a>)}</div></section>
    <section className="getting-started"><div><p className="eyebrow">IN THE WORKSPACE</p><h2>Start with a button.</h2><p>Import a component and the shared stylesheet. Use the theme control in the corner to explore different colors.</p><a href="#/components?component=button">See button variations <ArrowRight size={15} /></a></div><pre><code>{'import { Button } from "@cortex/ui";\nimport "@cortex/ui/styles.css";\n\n<Button variant="outline">\n  Create project\n</Button>'}</code><Terminal size={17} /></pre></section>
  </div>;
}
